# Much of this script was adapted from astropy/astropy.

language: python

env:
    global:
        - NUMPY_VERSION=1.8

matrix:
    include:
        # All the versions of Python.
        - python: 2.6
        - python: 2.7
        - python: 3.3
        - python: 3.4

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n testing python=$TRAVIS_PYTHON_VERSION
    - source activate testing
    - conda install --yes numpy=$NUMPY_VERSION nose pip numba cython pandas
    - pip install gensim

script:
    - ls
    - pwd
    - env | sort
    - nosetests -v
